LOG_DIR = 'logs'
LOG_STEM_PREFIX = 'DesksetBack'
LOG_STEM_FORMAT = 'YYYYMMDDHHmmss'
LOG_EXTN = 'log'

DEFAUKT_SERVER_HOST = '127.0.0.1'
DEFAUKT_SERVER_PORT = 6527

SHUTDOWN_TIMEOUT = 5  # 服务器从 Ctrl+C 到强制关闭的超时时间（秒）
