name: DesksetFront Tauri Auto Build


on:
  push:
    tags:
      # git tag -a v0.0.0  带注释的标签
      # git push && git push --tags  连提交带标签一起推送
        # PowerShell 用 git push; git push --tags
      - 'v*.*.*'


jobs:
  release:
    name: Build and Release

    runs-on: ${{ matrix.os }}

    env:
      # PowerShell 通过 $env:VARIABLE 访问环境变量
      DIST: "out/Deskset"
      DESKSETBACK_URL: "https://github.com/Nostalgia-Season-Train/DesksetBack-Release/releases/download/v0.0.1/DesksetBack-v0.0.1.zip"
      DESKSETUPDATER_URL: "https://github.com/Nostalgia-Season-Train/DesksetUpdater/releases/download/v0.0.1/DesksetUpdater.zip"

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    # 第一步：检出（下载）仓库
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 第二步：安装 NodeJS
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 第三步：下载依赖
    - name: Install Dependencies
      run: |
        npm install

    # 第四步：构建 Tauri
      # 复制 Deskset.exe
    - name: Build
      run: |
        New-Item -ItemType Directory -Path $env:DIST

        ./build.bat
        Copy-Item -Path "./setBottom.dll" -Destination "./$env:DIST/"

        npm run build
        Copy-Item -Path "./src-tauri/target/release/Deskset.exe" -Destination "./$env:DIST/"

    # 第五步：下载数字桌搭后端和数字桌搭更新器
      # 压缩包名称（-OutFile 设置），解压路径 = DesksetBack
    - name: Download DesksetBack
      run: |
        Invoke-WebRequest -Uri $env:DESKSETBACK_URL -OutFile "DesksetBack.zip"
        Expand-Archive -Path "./DesksetBack.zip" -DestinationPath "./$env:DIST/" -Force
        Remove-Item -Path "./DesksetBack.zip"
        Invoke-WebRequest -Uri $env:DESKSETUPDATER_URL -OutFile "DesksetUpdater.zip"
        Expand-Archive -Path "./DesksetUpdater.zip" -DestinationPath "./$env:DIST/" -Force
        Remove-Item -Path "./DesksetUpdater.zip"

    # 第六步：压缩目录
      # ./$env:DIST/ 会连文件夹一起压缩，用 ./$env:DIST/* 只包含文件夹内容
        # Deskset.zip/Deskset/XXX 跟 Deskset.zip/XXX 的区别
    - name: Zip
      run: |
        Compress-Archive -Path "./$env:DIST/*" -DestinationPath "./Deskset.zip" -CompressionLevel Optimal

    # 第七步：发布
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "Deskset.zip"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
